name: Dev Build

on:
  push:
    branches:
      - develop

env:
  SHA7: ${GITHUB_SHA::7}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Build
      run: |
        npm ci
        npm run build
      env:
        CI: true
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: modation-dev-${{ env.SHA7 }}
        path: rel
