name: Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.github_token}}

    # - name: Generate build version
    #   id: buildversion
    #   run: echo "::set-output name=build_version::$(node -p \"require('./package.json').version\")+${{ steps.buildnumber.outputs.build_number }}"

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: Build and pack extension
      run: |
        npm ci
        npm run build
        npm run pack
      env:
        CI: true

    - name: Upload release source artifact
      uses: actions/upload-artifact@v1
      with:
        name: modation-dev+${{ steps.buildnumber.outputs.build_number }}
        path: rel

    - name: Upload packed extension artifact
      uses: actions/upload-artifact@v1
      with:
        name: modation-dev+${{ steps.buildnumber.outputs.build_number }}
        path: build/modation.crx
